name: Release Pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Build
      run: |
        dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true
        
    - name: Read Release Notes
      id: release_notes
      shell: pwsh
      run: |
        $notes = Get-Content "RELEASE_NOTES.md" -Raw
        $notes = $notes -replace '\r\n', '%0A'
        echo "::set-output name=content::$notes"
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: bin/Release/net6.0/win-x64/publish/ScreensaverAuditor.exe
        body: ${{ steps.release_notes.outputs.content }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
